<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome !!</title>
</head>
<body bgcolor="#f5f5dc">
<div style="margin-top: 10px">Greetings,</div>
<br/>
<div>Welcome <b>${user.username}</b> <b>${user.prenom}</b>  </div>
<br/>
<div> It's small freemarker-springboot project test ;)</div>
<br/>
<div> Have a nice day..!</div>
</body>
</html>
